"""Closed-form forward and inverse kinematics for Gray's 3-DOF legs.

Pure Python + NumPy on purpose: this module runs unchanged in the simulator and on
the Raspberry Pi, which will never have MuJoCo installed. One code path, so a gait
tuned in simulation is the same gait that runs on the robot.

GEOMETRY
--------
Each leg is:

    trunk --[mount]--> hip --[q0 about X]--> thigh --[q1 about Z]-->
    shank --[q2 about Z]--> foot

q0 abducts about the fore-aft axis; q1 and q2 are hip-pitch and knee, and they share
an axis. That shared axis is what makes this solvable in closed form: because both
pitch joints rotate about Z of the hip frame, the foot's Z coordinate in that frame
is a CONSTANT (`lateral_offset`) no matter what q1 and q2 do. So the problem splits
cleanly into

    1. one rotation (q0) that swings a rigid plane about X, and
    2. a planar 2-link reach (q1, q2) inside that plane.

Both steps have exact solutions - no iteration, no Jacobian, no convergence checks.
That matters at 50 Hz on a Pi.

BRANCHES
--------
A 2-link chain reaching a point has two elbow solutions, and the abduction step has
two more (foot on either side of the roll axis). `inverse()` returns whichever valid
solution sits closest to a reference pose, which keeps the leg on one branch instead
of snapping between them mid-stride.

Parameters come from gray/config/robot.yaml, generated by tools/extract_kinematics.py.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from functools import lru_cache

import numpy as np
import yaml

LEGS = ("fl", "fr", "br", "bl")
_DEFAULT_CONFIG = os.path.join(os.path.dirname(__file__), "config", "robot.yaml")


def _rot_z(a: float) -> np.ndarray:
    c, s = np.cos(a), np.sin(a)
    return np.array([[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]])


def _rot_x(a: float) -> np.ndarray:
    c, s = np.cos(a), np.sin(a)
    return np.array([[1.0, 0.0, 0.0], [0.0, c, -s], [0.0, s, c]])


def _quat_to_mat(q: np.ndarray) -> np.ndarray:
    """MuJoCo/URDF scalar-first quaternion (w, x, y, z) -> rotation matrix."""
    w, x, y, z = q
    return np.array([
        [1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
        [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
        [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)],
    ])


@dataclass(frozen=True)
class Leg:
    """One leg's geometry, in its own hip frame unless stated otherwise."""

    name: str
    mount_pos: np.ndarray      # hip mount in trunk frame
    mount_rot: np.ndarray      # hip mount orientation in trunk frame
    abduct_sign: float         # +1 / -1: direction of the q0 axis
    pitch_sign: float          # +1 / -1: direction of the q1 axis
    knee_sign: float           # +1 / -1: direction of the q2 axis
    hip_to_thigh: np.ndarray   # hip origin -> hip-pitch joint
    thigh_len: float
    shank_len: float
    lateral_offset: float      # constant foot offset along the shared pitch axis
    thigh_zero: float          # in-plane direction of the thigh at q1 = 0
    shank_zero: float          # in-plane direction of the shank at q2 = 0

    # ---- forward ----------------------------------------------------------------

    def _planar(self, q1: float, q2: float) -> np.ndarray:
        """Foot position in the hip frame, before abduction."""
        a = self.thigh_zero + self.pitch_sign * q1
        b = a + self.shank_zero - self.thigh_zero + self.knee_sign * q2
        xy = (self.hip_to_thigh[:2]
              + self.thigh_len * np.array([np.cos(a), np.sin(a)])
              + self.shank_len * np.array([np.cos(b), np.sin(b)]))
        return np.array([xy[0], xy[1], self.lateral_offset])

    def forward(self, q: np.ndarray) -> np.ndarray:
        """Joint angles (q0, q1, q2) -> foot position in the TRUNK frame."""
        local = _rot_x(self.abduct_sign * q[0]) @ self._planar(q[1], q[2])
        return self.mount_pos + self.mount_rot @ local

    # ---- inverse ----------------------------------------------------------------

    def inverse(self, target: np.ndarray, reference: np.ndarray | None = None
                ) -> np.ndarray:
        """Foot position in the TRUNK frame -> joint angles (q0, q1, q2).

        Raises ValueError if the target is outside the leg's reachable workspace.
        """
        solutions = self._all_solutions(target)
        if not solutions:
            reach = self.thigh_len + self.shank_len
            raise ValueError(
                f"{self.name}: foot target {np.round(target, 4)} unreachable "
                f"(leg spans at most {reach*1000:.0f} mm)")
        if reference is None:
            reference = np.zeros(3)
        return min(solutions, key=lambda s: float(np.sum((s - reference) ** 2)))

    def _all_solutions(self, target: np.ndarray) -> list[np.ndarray]:
        v = self.mount_rot.T @ (np.asarray(target, float) - self.mount_pos)
        z0 = self.lateral_offset

        # --- step 1: abduction. Rx maps (Py, z0) onto (v.y, v.z), so their radii
        # must match; that pins |Py| and then the rotation angle follows directly.
        radial = v[1] ** 2 + v[2] ** 2 - z0 ** 2
        if radial < 0.0:
            return []  # target closer to the roll axis than the leg's fixed offset
        py_mag = np.sqrt(radial)

        out: list[np.ndarray] = []
        for py in ({py_mag, -py_mag} if py_mag > 1e-9 else {0.0}):
            theta = np.arctan2(v[2], v[1]) - np.arctan2(z0, py)
            q0 = self._wrap(theta) / self.abduct_sign

            # --- step 2: planar 2-link reach to (v.x, py) in the hip frame.
            t = np.array([v[0], py]) - self.hip_to_thigh[:2]
            d = float(np.hypot(*t))
            a, b = self.thigh_len, self.shank_len
            k = (d * d - a * a - b * b) / (2.0 * a * b)
            if not -1.0 <= k <= 1.0:
                continue  # out of reach on this branch
            base = np.arccos(k)

            for elbow in (base, -base):
                # interior angle between the two segments -> knee angle
                q2 = self._wrap(elbow - (self.shank_zero - self.thigh_zero)) \
                    / self.knee_sign
                # direction of the summed segments before the hip-pitch rotation
                ang = self.shank_zero - self.thigh_zero + self.knee_sign * q2
                w = np.array([a + b * np.cos(ang), b * np.sin(ang)])
                q1 = self._wrap(np.arctan2(t[1], t[0]) - np.arctan2(w[1], w[0])
                                - self.thigh_zero) / self.pitch_sign
                out.append(np.array([q0, q1, q2]))
        return out

    @staticmethod
    def _wrap(a: float) -> float:
        """Wrap to (-pi, pi]."""
        return float((a + np.pi) % (2.0 * np.pi) - np.pi)


@lru_cache(maxsize=4)
def load_legs(config_path: str = _DEFAULT_CONFIG) -> dict[str, Leg]:
    """Load every leg's geometry from robot.yaml."""
    with open(config_path) as fh:
        cfg = yaml.safe_load(fh)
    if "legs" not in cfg:
        raise SystemExit(f"{config_path} has no 'legs' section - run "
                         f"tools/extract_kinematics.py first")

    legs = {}
    for name, p in cfg["legs"].items():
        legs[name] = Leg(
            name=name,
            mount_pos=np.array(p["mount_pos"], float),
            mount_rot=_quat_to_mat(np.array(p["mount_quat"], float)),
            abduct_sign=float(np.sign(p["abduct_axis"][0])),
            pitch_sign=float(p["pitch_sign"]),
            knee_sign=float(p["knee_sign"]),
            hip_to_thigh=np.array(p["hip_to_thigh"], float),
            thigh_len=float(p["thigh_len"]),
            shank_len=float(p["shank_len"]),
            lateral_offset=float(p["lateral_offset"]),
            thigh_zero=float(p["thigh_zero_rad"]),
            shank_zero=float(p["shank_zero_rad"]),
        )
    return legs


def joint_vector(per_leg: dict[str, np.ndarray]) -> np.ndarray:
    """Pack {leg: (q0,q1,q2)} into the 12-vector MuJoCo and the servo driver use."""
    return np.concatenate([np.asarray(per_leg[leg], float) for leg in LEGS])


def split_joints(q: np.ndarray) -> dict[str, np.ndarray]:
    """Inverse of joint_vector()."""
    q = np.asarray(q, float)
    return {leg: q[3 * i: 3 * i + 3] for i, leg in enumerate(LEGS)}
